wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.29
    code_path: code/grasp/src/sean_approach/offline.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
    t:
      1:
      - 1
      4: 3.6.9
      5: 0.10.29
      8:
      - 5
densenet_lr:
  desc: null
  value: 5.0e-05
discount_factor:
  desc: null
  value: 0.9
iteration:
  desc: null
  value: 500
learning_rate:
  desc: null
  value: 0.00025
memory_size:
  desc: null
  value: 1328
mini_batch_size:
  desc: null
  value: 10
save_freq:
  desc: null
  value: 10
updating_freq:
  desc: null
  value: 10
